config/routes.rb
Ofx::Application.routes.draw do

  resources :links
  
  post 'admin/home_heroes', to: 'home_heroes#create_and_update'

  resources :standard_changes
  get 'standard_changes/:id/archive', to: 'standard_changes#archive'
  
  resources :comments, :except => [:index]
  
  resources :versions, except: [:index]
  
  devise_for :users, controllers: { sessions: 'sessions', registrations: 'registrations', passwords: 'passwords' }
  
  resources :users, except: [:new, :create]
  post 'users/new_by_admin',          to: 'users#new_by_admin'
  
  scope :ajax do
    get 'users/toggle',               to: 'users#toggle'
    get 'api_docs/start_stream',      to: 'api_docs#start_stream'
    get 'api_docs/update',            to: 'api_docs#update'
    get 'api_docs/insert_nav',        to: 'api_docs#insert_nav'
    get 'api_docs/test',              to: 'api_docs#test'
  end
  
  

  root to: 'welcome#index'
  

  resources :companies
  resources :contents
  get 'contents/page/:ident', to: "contents#page_display"
  
  resources :minutes
  get '/minutes/ajax/toggle_published', to: 'minutes#toggle_published'
  
  resources :news_items
  
  get   '/contact_form',        to: "contact_form#display"
  post  '/contact_form',        to: "contact_form#send_form_mail"
  
  get 'admin/dashboard', to: 'admin#dashboard'
end

app/models/content.rb
class Content < ActiveRecord::Base
  include Ofx::HtmlSanitizer
  
  has_attached_file :image, :styles => { :listing => "50x50", :display => "200x200" }, :default_url => "images/:style/missing.png"
  has_attached_file :pdf, :styles => { :thumbnail => "50x50" }
   
  before_validation :sanitize_textareas
  validates :identifier, :presence => true, :length => { maximum: 50 }, :format => { with: /[a-z0-9_]/, message: "Please user lowercase alphanumeric and underscore (_) only" }
  validates :title, :presence => true
  validates :published, :inclusion => { in: [true, false] }
  
  validates_attachment_content_type :image, :content_type => /\Aimage/
  validates_attachment_file_name :image, :matches => [ /png\Z/, /jpe?g\Z/, /gif\Z/ ]
  validates_attachment_content_type :pdf, :content_type => "application/pdf"
  validates_attachment_file_name :pdf, :matches => [/pdf\Z/]

  def self.build_panel(key)
    Content.where(identifier: key, published: true).first
  end
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  
  before_action :require_admin, except: [:page_display]
  before_action :set_content, only: [:show, :edit, :update, :destroy]

  # GET /Contents
  def index
    @contents = Content.all
  end
  
  def show
  end

  def new
    @content = Content.new
  end

  def create
    @content = Content.new(content_params)
    
    if @content.save
      redirect_to @content, notice: "#{@content.identifier} was successfully saved."
    else
      render action: 'new'
    end
  end

  def update
    if @content.update(content_params)
      redirect_to @content, notice: "#{@content.identifier} was successfully updated."
    else
      render action: 'new'
    end
  end

  def destroy
    identifier = @content.identifier
    @content.destroy
    redirect_to contents_url, notice: '#{identifier} was successfully deleted.'
  end
  
  def page_display
    @content = Content.where(identifier: params[:ident]).first
  end
  
  private    
    # Use callbacks to share common setup or constraints between actions.
    def set_content
      @content = Content.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def content_params
      params[:content].permit(:identifier, :title, :content, :image, :pdf, :pdf_title, :published)
    end

end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/views/contents/_form.html.haml
= form_for @content, :html => { :class => "form-horizontal", :role => "form" } do |f|
  - if @content.errors.any?
    .alert.alert-danger
      %h2 "#{pluralize(@content.errors.count, "error")} prohibited this user from being saved:"
      %ul
        - @content.errors.full_messages.each do |msg|
          %li= msg
  - if @content and @content.published?
    - klass = "bg-success"
  - elsif @content and !@content.published?
    - klass = "bg-danger"
    
  %div{ :class => "form-group #{klass} checkbox" }
    Published?
    = f.check_box :published, :value => @content.published
  .form-group
    = f.label :identifier
    = f.text_field :identifier, :value => @content.identifier, :class => "form-control"
  
  .form-group
    = f.label :title
    = f.text_field :title, :value => @content.title, :class => "form-control"
    
  .form-group
    = f.label :content
    = f.text_area :content, :value => @content.content, :class => "tinymce form-control", :rows => 20
  
  = field_set_tag 'PDF attachment' do
    .form-group
      = f.label :title
      = f.text_field :pdf_title, :value => @content.pdf_title, :class => "form-control"
       
    .form-group
      = f.label :pdf
      = f.file_field :pdf
      - if !@content.pdf.blank?
        = image_tag 'pdf_icon.png'
        = @content.pdf.name

  .form-group
    = f.label :image
    = f.file_field :image
    - if !@content.image.blank?
      = image_tag @content.image.url(:display)
      = @content.image.name

  .form-group
    = f.submit 'Save'
    
= render :partial => 'components/tinymce'

app/views/contents/edit.html.haml
.container
  .panel.panel-default
    .panel-heading
      %h1.panel-title Edit content
    .panel-body
      .row
        .col-lg-offset-1.col-lg-10
          = render 'form'

  = render :partial => 'components/back_dash_edit', :locals => { model: 'content', instance: @content, edit_page: true }

app/views/contents/index.html.haml
.container
  %h1 Content
  - if @contents.blank?
    %p There are no content items.
  - else
    %table.table
      %thead
        %tr
          %th 
          %th Identifier
          %th Title
          %th PDF
      %tbody
        - @contents.each do |content|
          %tr
            %td
              - if content.published?
                %button.published.btn.btn-xs.btn-success Unpublish
              - else
                %button.unpublished.btn.btn-xs.btn-primary Publish
            %td= content.identifier
            %td= content.title
            %td= content.pdf.blank? ? '(none)' : image_tag('pdf_icon.png')
            %td= render :partial => 'components/show_edit_delete', :locals => { :model => 'content', :instance => content }

  .btn.btn-default
    = link_to 'New Content', new_content_path, :type => 'button'

app/views/contents/new.html.haml
.container
  %h1 New content

  = render 'form'
    
  .btn-group        
    = link_to raw('<span class="glyphicon glyphicon-circle-arrow-left"></span> Back to Dashboard'), admin_dashboard_path, :type => 'button', :class => 'btn btn-default'

app/views/contents/page_display.html.haml
.container
  .col-md-offset-1.col-md-10
    - if @content.published?
      %h2= @content.title
      - unless @content.image.blank?
        .image.pull-right
          = image_tag @content.image(:display)
      = raw(@content.content)
      %p
        - unless @content.pdf.blank?
          = link_to image_tag('pdf_icon.png') << " " <<  @content.pdf_title, @content.pdf.url, :title => 'Articles of Association', :target => '_blank'
    - else
      %h2 Oops!
      %p Sorry, this isn't ready for prime time, yet.

  

app/views/contents/show.html.haml
.container
  .panel.panel-default
    .panel-heading
      - if @content.published
        - klass = "text-success"
      - else
        - klass = "text-danger"
      %h3.panel-title
        %div{:class => "#{klass}"}
          = @content.published? ? 'Published' : 'UNPUBLISHED'
    .panel-body
      - unless @content.image.blank?
        .image.pull-right
          = image_tag @content.image(:display)
      %p
        %strong Identifier:
        = @content.identifier
      %p
        %strong Title:
        = @content.title
      %label Content
      %p= raw(@content.content)
      %p
        - unless @content.pdf.blank?
          = link_to image_tag('pdf_icon.png') << " " <<  @content.pdf_title, @content.pdf.url, :title => 'Articles of Association', :target => '_blank'

  = render :partial => 'components/back_dash_edit', :locals => { model: 'content', instance: @content, edit_page: false }

  