config/routes.rb
Ofx::Application.routes.draw do

  resources :links
  
  post 'admin/home_heroes', to: 'home_heroes#create_and_update'

  resources :standard_changes
  get 'standard_changes/:id/archive', to: 'standard_changes#archive'
  
  resources :comments, :except => [:index]
  
  resources :versions, except: [:index]
  
  devise_for :users, controllers: { sessions: 'sessions', registrations: 'registrations', passwords: 'passwords' }
  
  resources :users, except: [:new, :create]
  post 'users/new_by_admin',          to: 'users#new_by_admin'
  
  scope :ajax do
    get 'users/toggle',               to: 'users#toggle'
    get 'api_docs/start_stream',      to: 'api_docs#start_stream'
    get 'api_docs/update',            to: 'api_docs#update'
    get 'api_docs/insert_nav',        to: 'api_docs#insert_nav'
    get 'api_docs/test',              to: 'api_docs#test'
  end
  
  

  root to: 'welcome#index'
  

  resources :companies
  resources :contents
  get 'contents/page/:ident', to: "contents#page_display"
  
  resources :minutes
  get '/minutes/ajax/toggle_published', to: 'minutes#toggle_published'
  
  resources :news_items
  
  get   '/contact_form',        to: "contact_form#display"
  post  '/contact_form',        to: "contact_form#send_form_mail"
  
  get 'admin/dashboard', to: 'admin#dashboard'
end

app/models/standard_change.rb
class StandardChange < ActiveRecord::Base
  include FriendlyId
  friendly_id :title, :use => :slugged
  
  include Ofx::HtmlSanitizer

  belongs_to :version
  belongs_to :sponsor, class_name: "User"
  belongs_to :last_editor, class_name: User
  
  acts_as_commentable
  has_many :comments, dependent: :destroy, as: :commentable
  
  scope :current, -> { where(archived: false) }
  scope :archived, -> { where(archived: true) }
  scope :recent_first, -> { includes(:version).order("versions.version DESC, standard_changes.status ASC, standard_changes.title ASC") }
  
  before_validation :sanitize_textareas
  validates :title, presence: true, length: { maximum: 100 }
  validates :type, inclusion: { in: Rails.configuration.ofx[:standard_change_type].keys.map{ |k| k.to_s }, message: 'is not a valid change type' }
  validates :status, inclusion: { in: Rails.configuration.ofx[:standard_change_status].keys.map{ |k| k.to_s }, message: 'is not a valid status' }

  # Because of Rails' penchant for single-table inheritance (:type would ordinarily indicate a subclass in this case),
  # we need to specify that there is no inheritance column
  
  self.inheritance_column = nil

  after_save :notify_subscribers
  
  # Notify subscribers when a standard change is updated.
  def notify_subscribers
    AdminMailer.notify_of_standard_change(self)
  end
  
  def self.build_panel(change_status, limit = 3)
    StandardChange.current.where(status: 'proposed').order("created_at DESC", "title ASC").limit(limit)
  end

  def saved_by(current_user)
    self.last_editor_id = current_user.id
    self.save
  end
  
  def updated_by(standard_change_params, current_user)
    self.last_editor_id = current_user.id
    self.update(standard_change_params)
  end
end

app/controllers/standard_changes_controller.rb
class StandardChangesController < ApplicationController
  before_action :set_standard_change, only: [:show, :edit, :update, :destroy]


  def archive
    @standard_change = StandardChange.find(params[:id])
    if @standard_change.update_attribute(:archived, params[:archived])
      render :json => { status: 'ok' }
    else
      render :json => { status: 'error' }
    end
  end  
  
  # GET /standard_changes
  def index
    if params[:archived]
      @standard_changes = StandardChange.archived.recent_first
      @archived = true 
    else
      @standard_changes = StandardChange.current.recent_first
      @archived = false 
    end
  end

  # GET /standard_changes/1
  def show
    @comment = @standard_change.comments.new
    @comments = @standard_change.comments.recent
  end

  # GET /standard_changes/new
  def new
    @standard_change = StandardChange.new
  end

  # GET /standard_changes/1/edit
  def edit
  end

  # POST /standard_changes
  def create
    @standard_change = StandardChange.new(standard_change_params)

    if @standard_change.saved_by(current_user)
      redirect_to @standard_change, notice: 'Standard change was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /standard_changes/1
  def update
    if @standard_change.updated_by(standard_change_params, current_user)
      redirect_to @standard_change, notice: 'Standard change was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /standard_changes/1
  def destroy
    @standard_change.destroy
    redirect_to standard_changes_url, notice: 'Standard change was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_standard_change
      @standard_change = StandardChange.friendly.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def standard_change_params
      params.require(:standard_change).permit(:version_id, :committee, :title, :type, :status, :status_details, :overview, :solution, :discussion, :archived)
    end
end

app/helpers/standard_changes_helper.rb
module StandardChangesHelper
  def get_change_selection(type)
    Rails.configuration.ofx["standard_change_#{type.to_s}".to_sym].map { |k, v| [v, k] }
  end  
end

app/views/standard_changes/_form.html.haml
= form_for @standard_change, :html => { :class => "form-horizontal", :role => "form" } do |f|
  - if @standard_change.errors.any?
    .alert.alert-danger
      %h2 #{pluralize(@standard_change.errors.count, "error")} prohibited this change from being saved:
      %ul
        - @standard_change.errors.full_messages.each do |msg|
          %li= msg

  - if @standard_change
    - case @standard_change.status
      - when 'approved'
        - klass = "bg-success"
      - when 'proposed'
        - klass = "bg-warning"
      - when 'withdrawn'
        - klass = "bg-danger"
  
  .form-group
    = f.check_box :archived, :value => @standard_change.archived
    = f.label "Archived"

  .form-group  
    = f.label :version
    = f.collection_select :version_id, Version.order(version: :desc), :id, :version, :class => "form-control"

  .form-group
    = f.label :status
    = f.select :status, options_for_select(get_change_selection(:status), (@standard_change.status.blank? ? 'proposed' : @standard_change.status)), :class => "form-control"

  .form-group
    = f.label :title
    = f.text_field :title, :value => @standard_change.title, :class => "form-control" 

  .form-group
    = f.label :type
    = f.select :type, options_for_select(get_change_selection(:type), @standard_change.type), :class => "form-control"
    
  .form-group
    = f.label :subcommittee
    = f.text_area :committee, :value => @standard_change.committee, :class => "tinymce form-control", :rows => 7

  .form-group
    = f.label :overview
    = f.text_area :overview, :value => @standard_change.overview, :class => "tinymce form-control", :rows => 7

  .form-group
    = f.label :solution
    = f.text_area :solution, :value => @standard_change.solution, :class => "tinymce form-control", :rows => 15

  .form-group
    = f.label 'Final status'
    .hint.text-muted (Please fill this in when the change is approved)
    = f.text_area :status_details, :value => @standard_change.status_details, :class => "tinymce form-control", :rows => 7
    
    = f.hidden_field :last_editor_id, :value => current_user.id
    
  .form-group
    = f.submit 'Save'
    
= render :partial => 'components/tinymce'

app/views/standard_changes/edit.html.haml
.container
  .panel.panel-default
    .panel-heading
      %h1.panel-title Edit standard change
    .panel-body
      .row
        .col-lg-offset-1.col-lg-10
          = render 'form'

  = render :partial => 'components/back_dash_edit', :locals => { model: 'standard_change', instance: @standard_change, edit_page: true }

app/views/standard_changes/index.html.haml
.container
  %h1 Standard Changes
  - if @standard_changes.blank?
    %p There are currently no #{@archived ? 'archived ' : ''}standard changes.
  - else
    - if user_signed_in? and current_user.has_role? :admin
      .row
        - unless @archived
          .col-md-2
            .btn.btn-default
              = link_to 'New standard change', new_standard_change_path, :type => 'button'
          .col-md-2
            .btn.btn-warning
              = link_to 'Archived standard changes', "#{standard_changes_path}?archived=true", :type => 'button'
        - else
          .col-md-2
            .btn.btn-success
              = link_to 'Current standard changes', "#{standard_changes_path}", :type => 'button'
      %br
    .row   
      .col-md-2
        .form-group
          = select_tag('status', options_for_select([["Any status", "all"]] + get_change_selection('status'),'proposed'), class: 'status form-control input-small')
      .col-md-2
        .form-group
          = select_tag('version', options_for_select([["All versions", "all"]] + get_version_options), class: 'version form-control input-small')
      .col-md-6
        %span.sc-key.bg-info Proposed
        != "&nbsp;&nbsp;&nbsp;"
        %span.sc-key.bg-success Approved
        != "&nbsp;&nbsp;&nbsp;"
        %span.sc-key.bg-danger Withdrawn or Deprecated
    .table-responsive
      %table.table
        %tr
          %th Version
          %th Title
          %th Overview
          %th Activity
          %th Type
          %th Status

        - @standard_changes.each_with_index do |standard_change, i|
          - klass = "v#{standard_change.version.version.gsub('.','')} #{standard_change.status}"
          - case standard_change.status
            - when 'approved'
              - klass += ' success'
            - when 'proposed'
              - klass += ' info'
            - when 'withdrawn', 'deprecated'
              - klass += ' danger'
          - if i > 0 and @standard_changes[i-1].version.version != standard_change.version.version
            - klass += ' new-version-row'
          %tr{ class: klass }
            %td{:class => standard_change.version.current? ? 'current' : ''}= standard_change.version.version
            %td
              %b
                = standard_change.title
              %br
              %br
              = render :partial => 'components/show_edit_delete', :locals => { :model => 'standard_change', :instance => standard_change }
              %br
              %br
              - if user_signed_in? and current_user.has_role? :admin
                .archive
                  = check_box_tag "archived", standard_change.archived? ? '1' : '0', standard_change.archived?, class: "#{standard_change.id}"
                  Archive
            - overview = standard_change.overview.gsub(%r|<pre>.*</pre>|m, '') unless standard_change.overview.nil?
            %td.overview
              = truncate_html(raw(overview), :length => 400)
            %td
              %em
                != "Last&nbsp;updated:<br />#{standard_change.updated_at.strftime('%e %b \'%y')}"
              %br
              - last_commented = standard_change.comments.blank? ? 'never' : standard_change.comments.last.created_at.strftime('%e %b \'%y')
              %em
                !="Last&nbsp;commented:<br />#{last_commented}"
            %td= standard_change.type
            %td= standard_change.status
 
  - if user_signed_in? and current_user.has_role? :admin
    %br
    .btn.btn-default
      = link_to 'New Standard change', new_standard_change_path, :type => 'button'

app/views/standard_changes/new.html.haml
.container
  %h1 New standard change

  = render 'form'


  .btn-group        
    = link_to raw('<span class="glyphicon glyphicon-circle-arrow-left"></span> Back to List'), standard_changes_path, :type => 'button', :class => 'btn btn-default'

app/views/standard_changes/show.html.haml
- case @standard_change.status
  - when 'approved'
    - klass = "panel-success"
    - status = 'Approved'
  - when 'proposed'
    - klass = "panel-warning"
    - status = 'Proposed'
  - when 'withdrawn'
    - klass = "panel-danger"
    - status = 'Withdrawn'
.container
  .row
    .col-md-offset-2.col-md-8    
      = render :partial => 'components/back_dash_edit', :locals => { model: 'standard_change', instance: @standard_change, edit_page: false }
      %br
      %br
      .panel{ class: klass }
        .panel-heading
          %h3.panel-title
            = @standard_change.title
            %span{:class => "pull-right"}= status
        .panel-body
          %p
            %b Standard version:
            = @standard_change.version.version

          %p
            %b= "#{Rails.configuration.ofx[:standard_change_type][@standard_change.type.to_sym]} Change"

          - if @standard_change.status == 'approved'
            %label Final status
            = raw(@standard_change.status_details)
  
          %label Subcommittee
          %p= raw(@standard_change.committee)

          %label Overview
          = raw(@standard_change.overview)

          %label Solution
          = raw(@standard_change.solution)

      = render :partial => 'components/back_dash_edit', :locals => { model: 'standard_change', instance: @standard_change, edit_page: false }
      %br
      %br

      = render :partial => 'comments/comments'
      
      = render :partial => 'components/back_dash_edit', :locals => { model: 'standard_change', instance: @standard_change, edit_page: false }
 