config/routes.rb
Ofx::Application.routes.draw do

  resources :links
  
  post 'admin/home_heroes', to: 'home_heroes#create_and_update'

  resources :standard_changes
  get 'standard_changes/:id/archive', to: 'standard_changes#archive'
  
  resources :comments, :except => [:index]
  
  resources :versions, except: [:index]
  
  devise_for :users, controllers: { sessions: 'sessions', registrations: 'registrations', passwords: 'passwords' }
  
  resources :users, except: [:new, :create]
  post 'users/new_by_admin',          to: 'users#new_by_admin'
  
  scope :ajax do
    get 'users/toggle',               to: 'users#toggle'
    get 'api_docs/start_stream',      to: 'api_docs#start_stream'
    get 'api_docs/update',            to: 'api_docs#update'
    get 'api_docs/insert_nav',        to: 'api_docs#insert_nav'
    get 'api_docs/test',              to: 'api_docs#test'
  end
  
  

  root to: 'welcome#index'
  

  resources :companies
  resources :contents
  get 'contents/page/:ident', to: "contents#page_display"
  
  resources :minutes
  get '/minutes/ajax/toggle_published', to: 'minutes#toggle_published'
  
  resources :news_items
  
  get   '/contact_form',        to: "contact_form#display"
  post  '/contact_form',        to: "contact_form#send_form_mail"
  
  get 'admin/dashboard', to: 'admin#dashboard'
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @ofx_welcome = Content.build_panel('ofx_welcome')
    @companies = Company.build_panel
    @glossary = Content.build_panel('glossary')
    @news_items = NewsItem.build_panel
    @why_a_standard = Content.build_panel('why_a_standard')
    @info_for_implementers = Content.build_panel('info_for_implementers')
    @links_for_implementers = Link.build_panel
    @agm_minutes = Minute.build_panel('agm')
    @dir_minutes = Minute.build_panel('dirm')
    @proposed_standard_changes = StandardChange.build_panel('proposed')
  end
end

app/views/welcome/_agm_minutes.html.haml
%h3 General Meeting Minutes
- if @agm_minutes.blank?
  %p No minutes are available
- else    
  %ul.list-group.no-borders
    - @agm_minutes.each do |m|
      %li.list-group-item.no-borders
        = link_to "Minutes for AGM #{m.date.strftime('%Y')}", minute_path(m)
    %li.list-group-item.list-group-item-info
      =link_to "All meetings", minutes_path
      %span.glyphicon.glyphicon-circle-arrow-right

app/views/welcome/_dir_minutes.html.haml
%h3 Directors' Meeting Minutes
- if @dir_minutes.blank?
  %p No minutes are available
- else    
  %ul.list-group.no-borders
    - @dir_minutes.each do |m|
      %li.list-group-item.no-borders
        = link_to "Minutes for #{m.date.strftime('%e %b %Y')}", minute_path(m)
    %li.list-group-item.list-group-item-info
      =link_to "All meetings", minutes_path
      %span.glyphicon.glyphicon-circle-arrow-right

app/views/welcome/_info_for_implementers.html.haml
.panel.panel-info
  .panel-heading
    %h3.panel-title Info
  .panel-body
    - if !@info_for_implementers.nil?
      = raw(@info_for_implementers.content)
    - else
      %p.text-danger Please create content with a key of 'info_for_implementers'

app/views/welcome/_links_for_implementers.html.haml
.panel.panel-info
  .panel-heading
    %h3.panel-title Useful Links
  .panel-body
    %ul.list-group.no-borders
    - @links_for_implementers.each do |link|
      %li.list-group-item.no-borders
        = link_to link.title, link.url, :target => /http/.match(link.url) ? '_blank' : 'self'
    - if !user_signed_in?
      %p
        = link_to 'Register as a site user', new_user_registration_path, :class => 'btn btn-sm btn-warning'

app/views/welcome/_panel_1.html.haml
%h2 Member Companies
%ul.list-group.no-borders
- @companies[:obj].each do |company|
  %li.list-group-item.no-borders
    - if @companies[:use_logos]
      = link_to image_tag(company.logo(:listing)), company_path(company)
    = link_to company.name, company_path(company)

app/views/welcome/_panel_2.html.haml
%h2= @glossary.title
= raw(@glossary.content)

app/views/welcome/_panel_members.html.haml
%h2 Member Companies
%ul.list-group.no-borders
- @companies[:obj].each do |company|
  %li.list-group-item.no-borders
    - if @companies[:use_logos]
      = link_to image_tag(company.logo(:listing)), company_path(company)
    = link_to company.name, company_path(company)

app/views/welcome/_panel_news.html.haml
%h2 News
.panel.panel-primary
  .panel-heading
    %h3.panel-title The Latest from Open FX
  .panel-body
    - if @news_items.blank?
      %p There are no news items at this time.
    - else    
      %ul.no-bullets
        - @news_items.each do |item|
          %li.headline
            = link_to item.headline, news_item_path(item)

app/views/welcome/_panel_terminology.html.haml
%h2= @glossary.title
= raw(@glossary.content)

app/views/welcome/_standard.html.haml
%h2 Why a Standard?
= raw(@why_a_standard.content)

app/views/welcome/_standards_discussion.html.haml
%h3 Standards Discussion
- if @proposed_standard_changes.blank?
  %p No standard changes are proposed at this time
- else
  %ul.list-group.no-borders    
    - @proposed_standard_changes.each do |change|
      %li.list-group-item.no-borders
        = link_to change.title, standard_change_path(change)
    %li.list-group-item.list-group-item-info
      = link_to 'All standard changes', standard_changes_path
      %span.glyphicon.glyphicon-circle-arrow-right

app/views/welcome/_welcome.html.haml
- if @ofx_welcome
  %h2= @ofx_welcome.title
  = raw(@ofx_welcome.content)

app/views/welcome/index.html.haml
.welcome#welcome
  .container
    .jumbotron
      .logo= image_tag('ofx_logo.png')
      %h1 
        Welcome to
        %br The Open Effects Association
      = #{@welcome_content}

.welcome.bg-info
  .container
    .row
      .col-sm-offset-2.col-sm-8
        = render :partial => 'welcome'
      
#panels.welcome
  .container
    .row
      .col-md-4
        = render :partial => 'panel_news'
      .col-md-4
        = render :partial => 'panel_terminology'
      .col-md-4
        = render :partial => 'panel_members'

#standard.welcome
  .container
    .row
      .col-sm-offset-2.col-sm-8
        = render :partial => 'standard' 

#implementers.welcome
  .container
    .row
      .col-sm-offset-2.col-sm-8
        %h2 For Implementers
        .col-md-6
          = render 'info_for_implementers'
        .col-md-6
          = render 'links_for_implementers'
  
#organization.welcome
  .container
    .row
      %h2 Association Business

    .row
      .col-md-4
        = render 'standards_discussion'
      .col-md-4
        = render 'agm_minutes'
      .col-md-4
        = render 'dir_minutes'
        
    
    
      
      